### ISSUE TITLE
Connections issues - step00

### ISSUE THREAD

**Issue by javixeneize** [leucos/ansible-tuto#101]
Hi

I am unable to connect to vagrant using ansible-playbook -c paramiko -i step-00/hosts step-00/setup.yml --ask-pass --become

I am having an error - fatal: [host0.example.org]: UNREACHABLE! => {"changed": false, "msg": "Authentication failed.", "unreachable": true}

I can connect to it via ssh directly (vagrant ssh host0 or ssh -p 2222 vagrant@localhost)

I dont have any keys stored in the VM or my machine, as the tutorial says it is not needed (While this is not absolutely necessary (Ansible can use sudo, password authentication, etc...), it will make things way easier.)

Could this be the problem?

Thanks

**Comment by leucos** [comment]
@javixeneize yes indeed, the step-00/setup.yml playbook looks for your public key in `~/.ssh/id_rsa.pub`. Sure, everything an be done by other means, but since this is a tutorial, it would be quite cumbersome.

May be you can generate one juste for the tutorial wih `ssh-keygen -t rsa` ?

**Comment by leucos** [comment]
Wait no, this is not the problem. The SSH keys wirll be required for the next tutotial steps, but it should not prevent you from connection since the purpose of the first playbook is to add your SSH key.

When you connect, do you have a SSH warning about `Offending RSA key` ? If yes, please remove existing keys for the 3 IPs (192.168.33.10, 192.168.33.11, 192.168.33.12) from your `~./.ssh/known_hosts` file.

You can alsto try the same command removing the `-c paramiko` part and see how it goes.

**Comment by javixeneize** [comment]
No keys at all stored. By removing paramiko i have a timeout now...

**Comment by javixeneize** [comment]
Ah wait... vagrant was down... same issue removing paramiko

Password is vagrant right?

**Comment by leucos** [comment]
Yes it is.
I've made a change (on master) that might improve things a bit. Could you `git pull`, `vagrant destroy -f`, `vagrant up` and ` ansible-playbook -i step-00/hosts step-00/setup.yml --ask-pass --become` please ?

**Comment by leucos** [comment]
BTW what ansible version are you using ?

**Comment by javixeneize** [comment]
It works fine. Was it the cfg file?

I have 2.3.0.0

Thanks

**Comment by leucos** [comment]
Glad to hear. I guess you already had entries in your known hosts file for
the VM IPs.
Thanks & have fun with the tutorial !
