### ISSUE TITLE
step-10+ : jinja template refer to eth1

### ISSUE THREAD

**Issue by terroirman** [leucos/ansible-tuto#110]
#111 

In ubuntu 18.04, eth1 becomes enp0s8.

But that brings another question, how would you do it in the template ? Is there a way to dynamically generate the variable name ? Ie.: take the last entry from ansible_interfaces.

From what I've seen, its not possible.

How could it be done from the playbook ?

**Comment by leucos** [comment]
Well, I use `ansible_all_ipv4_addresses.1` in the playbook (updated today).
Working with interface names is not easy, since ansible does not provide interface as dict keys in facts.
So is is quite tricky.

For instance, if you need to know what IP interface `interface_name` (defined in inventory) has, you must do something like:

`host_vars[inventory_hostname]['ansible_' + interface_name].ipv4.address`

This is very inconvenient... but I do not have a better solution right now.

As always, networking & storage devices are the burden the story.

**Comment by terroirman** [comment]
Thanks for the feedback! I'll fetch the latest changes. Great tutorial by the way.
