### ISSUE TITLE
Step 00 - Fails if public key doesn't exists

### ISSUE THREAD

**Issue by bernardoVale** [leucos/ansible-tuto#82]
When you create a new Vagrant file, the public key for root it's inexistent.

    TASK: [Pushes user's rsa key to root's vagrant box (it's ok if this TASK fails)] ***
    failed: [192.168.33.10] => {"failed": true}
    msg: could not find src=/root/.ssh/id_rsa.pub
    ...ignoring
    failed: [192.168.33.11] => {"failed": true}
    msg: could not find src=/root/.ssh/id_rsa.pub
    ...ignoring
    failed: [192.168.33.12] => {"failed": true}
    msg: could not find src=/root/.ssh/id_rsa.pub
    ...ignoring

    TASK: [Pushes user's dsa key to root's vagrant box (it's NOT ok if both TASKs fail)] ***
    failed: [192.168.33.10] => {"failed": true}
    msg: could not find src=/root/.ssh/id_dsa.pub
    failed: [192.168.33.12] => {"failed": true}
    msg: could not find src=/root/.ssh/id_dsa.pub
    failed: [192.168.33.11] => {"failed": true}
    msg: could not find src=/root/.ssh/id_dsa.pub

The creation of this file it's quite simple but maybe isn't for newcomers and since this is a tutorial for first steps with Ansible maybe it's a good idea to also automate this first task.

**Comment by leucos** [comment]
Hi @bernardoVale .  It seems you're running vagrant as root instead of a regular user. Is there any reason to do so ?

**Comment by bernardoVale** [comment]
Hi @leucos, no, there's no particular reason. The same error occur using vagrant user

**Comment by leucos** [comment]
I was talking about the use on your host, not the guest VM. It seems, from the output above, that you are running as root on your machine. And it seems that 'root' on your machine has no ssh keys.

In this tutorial, you run ansible from your local machine, and ansible will configure VM guests. So you need your public key to be copied in root's authorized_keys in the guest VM.
The tutorial also assumes you have proper keys set-up already.

Patch #83 would create ssh-keys for user root _inside_ the guest (VM), so it wont' help

So I see may be two issues here:
- the documentation is not clear enough, and the setup should be explained more clearly/in more depth ("what runs where which configures what")
- we might have some users without a key pair, so this should be explained too.

However, if the user does not have a proper keypair (e.g. /home/bernardo/.ssh/id_rsa and /home/bernardo/.ssh/id_rsa.pub), I'd rather get him to ssh documentation instead of creating a pair for him/her; I don't think that it would be safe to do this magically, especially if these keys are reused in a more serious context.

Does all this makes sense ?

**Comment by bernardoVale** [comment]
Oh this explain a lot. So the intend is to use ansible on my local machine. So you're right, maybe it's better to alter the documentation, I'll close this issue.

Best regards.
